version: '3.7'
services:
    wodss_frontend:
        build: ./
        image: wodss/frontend:latest
        container_name: wodss_frontend
        restart: always
        ports:
          - "3000:3000"
        volumes:
          - .env:/app/.env # add the .env-file from the current directory as .env in the container